/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf -k -T
Author: Diego G. (https://sketchfab.com/empty_mirror)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/voxel-web-development-50ad959d6c6b4799806c45bfa46ca550
Title: Voxel Web Development
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { angleToRadian } from "utils/commonUtils";

export function LaptopModel(props) {
  const { nodes, materials } = useGLTF(
    process.env.PUBLIC_URL +
      "/assets/gltfs/voxel_web_development/scene-transformed.glb"
  );

  return (
    <group {...props} scale={[5, 5, 5]} dispose={null}>
      <mesh
        name="Object_4"
        geometry={nodes.Object_4.geometry}
        material={materials.palette}
        rotation={[angleToRadian(90), 0, 1 * angleToRadian(90)]}
      />
      <mesh
        name="Object_6"
        geometry={nodes.Object_6.geometry}
        material={materials["palette.001"]}
        rotation={[angleToRadian(90), 0, 1 * angleToRadian(90)]}
      />
      <mesh
        name="Object_8"
        geometry={nodes.Object_8.geometry}
        material={materials["palette.002"]}
        rotation={[angleToRadian(90), 0, 1 * angleToRadian(90)]}
      />
    </group>
  );
}

useGLTF.preload(
  process.env.PUBLIC_URL +
    "/assets/gltfs/voxel_web_development/scene-transformed.glb"
);
